title: Tech and working with it
description: Learnins and reflections
author: Björn

# Publish posts with future dates
future: true

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Theme settings
theme: minima

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
