title: My Blog
description: A personal blog with Solarized Light theme
author: Your Name
email: your.email@example.com

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Theme settings
theme: minima

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
